<div class="container-fluid m-0 p-0">
        <!---->
        <div class="p-0 m-0">

            <div id="banner1" class="">
                <div class="fondo"></div>
                <!-- <img src="img/64684501_10157654834912708_7297900629979037696_o.jpg" class="w-100"> -->
                <video muted autoplay loop class="principal w-100">
                    <source src="video/principal.ogg" type="video/ogg">
                    <source src="video/principal.mp4" type="video/mp4">
                </video>

                <div class="d-none d-md-block text-banner">
                    <h1>Ven y Conoce Nicaragua</h1>
                    <h4 class="mt-3">Tierra de Lagos y Volcanes</h4>
                </div>

                <div class="contact">
                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                    <a href="#"><i class="fab fa-youtube"></i></a>
                    <a href="#"><i class="fab fa-pinterest-p"></i></a>
                </div>
            </div>
        </div>

        <div class="informacion row m-0 p-4 container-fluid text-white">

            <div class="col-sm-6 text-center col-md-3 py-4">
                <span class="fas fa-hotel my-2"></span>
                <h4>Hoteles</h4>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, veritatis!</p>
            </div>
            <div class="col-sm-6 text-center col-md-3 py-4">
                <span class="fas fa-hiking my-2"></span>
                <h4>Tours</h4>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, veritatis!</p>
            </div>
            <div class="col-sm-6 text-center col-md-3 py-4">
                <span class="fas fa-utensils my-2"></span>
                <h4>Restaurantes</h4>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, veritatis!</p>
            </div>
            <div class="col-sm-6 text-center col-md-3 py-4">
                <span class="fas fa-users my-2"></span>
                <h4>Interpretes</h4>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, veritatis!</p>
            </div>
        </div>

        <div class="container-fluid m-0 row my-3 hot p-1">
            <div class="contenedor-imagen col-md-5 m-0 p-0">
                <div class="fon"></div>
                <img src="<?= BASE_URL?>assets/img/hotel.jpg" class="">
                <div class="slayers d-flex flex-column align-content-center justify-content-center p-3">
                    <h2>HOTELES</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur, commodi dicta unde reiciendis aperiam doloremque.</p>
                    <a href="#" class="btn btn-primary text-decoration-none badge-pill">Read More <span class="fas fa-arrow-right"></span></a>
                </div>
            </div>

            <div class="d-none d-sm-block col-md-3 ml-lg-5 hotTar">
                <img src="<?= BASE_URL?>assets/img/hostales.jpg" class="img-fluid">
                <h3>titulo</h3>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniam est accusamus nesciunt blanditiis similique fugit.</p>
            </div>

            <div class="d-none d-sm-block col-md-3 ml-lg-5 hotTar">
                <img src="<?= BASE_URL?>assets/img/unnamed.jpg" class="img-fluid">
                <h3>titulo</h3>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniam est accusamus nesciunt blanditiis similique fugit.</p>
            </div>
        </div>

        <hr />

        <div class="container-fluid m-0 row my-3 hot p-1">
            <div class="contenedor-imagen col-md-5 m-0 p-0 order-2">
                <div class="fon"></div>
                <img src="<?= BASE_URL?>assets/img/unnamed.jpg" class="">
                <div class="slayers d-flex flex-column align-content-center justify-content-center p-3">
                    <h2>TOURS</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur, commodi dicta unde reiciendis aperiam doloremque.</p>
                    <a href="#" class="btn btn-primary text-decoration-none badge-pill">Read More <span class="fas fa-arrow-right"></span></a>
                </div>
            </div>

            <div class="d-none d-sm-block col-md-3 ml-lg-5 hotTar order-0">
                <img src="<?= BASE_URL?>assets/img/tour2.jpg" class="img-fluid">
                <h3>titulo</h3>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniam est accusamus nesciunt blanditiis similique fugit.</p>
            </div>

            <div class=" d-none d-sm-block col-md-3 ml-lg-5 hotTar order-1">
                <img src="<?= BASE_URL?>assets/img/tour3.jpg" class="img-fluid">
                <h3>titulo</h3>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniam est accusamus nesciunt blanditiis similique fugit.</p>
            </div>
        </div>


        <!-- Restaurante -->
        <div class="container-fluid caja mt-5">
            <div class="imag"></div>

            <div class="hoteles row justify-content-around m-auto">
                <div class="cajas text-center col-sm-12 mt-sm-2 col-md-3">
                    <h4 class="text-center m-auto p-2">titulo</h4>
                    <img src="img/hostales.jpg" class="mt-2" alt="">
                    <p class="m-auto p-2">Lorem ipsum dolor sit amet.</p>
                    <a href="#" class="btn btn-outline-primary my-2">Buscar Restaurante</a>
                </div>

                <div class="cajas text-center col-sm-5 mt-sm-2 col-md-3">
                    <h4 class="text-center m-auto p-2">titulo</h4>
                    <img src="img/hostales.jpg" class="mt-2" alt="">
                    <p class="m-auto p-2">Lorem ipsum dolor sit amet.</p>
                    <a href="#" class="btn btn-outline-primary my-2">Buscar Restaurante</a>
                </div>

                <div class="cajas text-center col-sm-5 mt-sm-2 col-md-3">
                    <h4 class="text-center m-auto p-2">titulo</h4>
                    <img src="img/hostales.jpg" class="mt-2" alt="">
                    <p class="m-auto p-2">Lorem ipsum dolor sit amet.</p>
                    <a href="#" class="btn btn-outline-primary my-2">Buscar Restaurante</a>
                </div>
            </div>
        </div>

        <!-- fin Restaurante -->

        <!-- principales Ciudades -->
        <div class="ciudades">
            <h2 class="p-3">Principales Ciudades</h2>

            <div class="col-md-12">
                <div class="owl-carousel owl-theme p-0">
                    <div class="item itemciu my-3">
                        <img src="img/somoto-canyon-national-monument.jpg" class="img-fluid" alt="4">
                        <div class="ciuCont">
                            <h4 class="mt-2 p-1 mt-2">Somoto</h4>
                            <p>
                                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed, nobis nihil? Sunt sint exercitationem iusto.
                            </p>
                            <a href="#" class="text-decoration-none text-white btn btn-primary btn-block w-75 m-auto badge-pill">Ir</a>
                        </div>
                    </div>

                    <div class="item itemciu my-3">
                        <img src="img/somoto-canyon-national-monument.jpg" class="img-fluid" alt="4">
                        <div class="ciuCont">
                            <h4 class="mt-2 p-1 mt-2">Ocotal</h4>
                            <p>
                                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed, nobis nihil? Sunt sint exercitationem iusto.
                            </p>
                            <a href="#" class="text-decoration-none text-white btn btn-primary btn-block w-75 m-auto badge-pill">Ir</a>
                        </div>
                    </div>

                    <div class="item itemciu my-3">
                        <img src="img/somoto-canyon-national-monument.jpg" class="img-fluid" alt="4">
                        <div class="ciuCont">
                            <h4 class="mt-2 p-1 mt-2">Esteli</h4>
                            <p>
                                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed, nobis nihil? Sunt sint exercitationem iusto.
                            </p>
                            <a href="#" class="text-decoration-none text-white btn btn-primary btn-block w-75 m-auto badge-pill">Ir</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- fin de principales Ciudades -->

        <div class="container-fluid">

            <h3 class="linea mt-5" id="color-n"><span>¿Porque reservar aquí?</span></h3>
            <div class="row">
                <div class="col-md-4 col-xs-12">
                    <div class="funciones text-center">
                        <i id="icon-funciones" class="fa fa-edit"></i>
                        <p class="mt-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam illo dolore iste iure magnam sunt dignissimos in.</p>
                    </div>
                </div>
                <div class="col-md-4 col-xs-12">
                    <div class="funciones text-center">
                        <i id="icon-funciones" class="fa fa-trash"></i>
                        <p class="mt-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam illo dolore iste iure magnam sunt dignissimos in.</p>
                    </div>
                </div>
                <div class="col-md-4 col-xs-12">
                    <div class="funciones text-center">
                        <i id="icon-funciones" class="fa fa-search"></i>
                        <p class="mt-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam illo dolore iste iure magnam sunt dignissimos in.</p>
                    </div>
                </div>
            </div>
        </div>

    </div>
