<div class="container">
    <form method="POST">
        <div class="row">
            <!-- grupo nombre -->
            <div class="form-group col-md-6">
                <label class="control-label" for="nombre">Nombres: </label>
                <input class="form-control" type="text" name="nombre" id="nombre" placeholder="Ingresa el Nombre">
                <?php if(isset($this->nombreError)) echo $this->nombreError;?>
            </div>

            <!-- grupo apellido -->
            <div class="form-group col-md-6">
                <label class="control-label">Apellido: </label>
                <input class="form-control" type="text" name="apellido" id="apellido" placeholder="Ingresa el Apellido">
                <?php if(isset($this->apellidoError)) echo $this->apellidoError;?>
            </div>
            <!-- grupo edad -->
            <div class="form-group col-md-6">
                <label class="control-label">Edad: </label>
                <input class="form-control" type="text" name="edad" id="edad">
                <?php if(isset($this->edadError)) echo $this->edadError;?>
            </div>
            <!-- grupo telefono -->
            <div class="form-group col-md-6">
                <label class="control-label">Teléfono: </label>
                <input class="form-control" type="text" name="telefono" id="telefono" placeholder="Número de Teléfono">
                <?php if(isset($this->telefonoError)) echo $this->telefonoError;?>
            </div>
            <!-- grupo telefono -->
            <div class="form-group col-md-6">
                <label class="control-label">Nacionalidad: </label>
                <input class="form-control" type="text" name="nacionalidad" id="nacionalidad" placeholder="Nacionalidad">
                <?php if(isset($this->nacionalidadError)) echo $this->nacionalidadError;?>
            </div>
            <!-- grupo telefono -->
            <div class="form-group col-md-6">
                <label class="control-label">Idioma: </label>
                <input class="form-control" type="text" name="idioma" id="idioma" placeholder="Idioma">
                <?php if(isset($this->idiomaError)) echo $this->idiomaError;?>
            </div>
        </div>
        <!-- Datos de la cuenta  -->
        <p class="style-p mt-3">Datos de la cuenta</p>
        <hr>
        <div class="row">
            <div class="form-group col-md-6">
                <label class="control-label formulario__label">Nombres de usuario: </label>
                <input class="form-control formulario-input" type="text" name="nombreUsuario" id="nombreUsuario" placeholder="Ingresa el Nombre">
                <?php if(isset($this->usuarioError)) echo $this->usuarioError;?>
            </div>
            <div class="form-group col-md-6">
                <label class="control-label">Correo: </label>
                <input class="form-control" type="email" name="correo" id="correo" placeholder="Ingresa correo electronico">
                <?php if(isset($this->correoError)) echo $this->correoError;?>
            </div>
            <div class="form-group col-md-6">
                <label class="control-label">Contraseña: </label>
                <input class="form-control" type="password" name="pass" id="pass" placeholder="Ingresa el nombre">
            </div>
            <div class="form-group col-md-6">
                <label class="control-label">Repetir Contraseña: </label>
                <input class="form-control" type="password" name="confirPass" id="confirPass" placeholder="Ingresa el nombre">
            </div>
            <div class="col-md-12"><?php if(isset($this->passwordError)) echo $this->passwordError;?></div>
        </div>
        <div class="row">

            <div class="text-center mt-3 mr-4 ml-3">
                <a href="<?= BASE_URL ?>index"><button class="btn btn-primary" type="button">Cancelar</button></a>
            </div>

            <div class="text-center mt-3">
                <input type="submit" value="Registrarse" class="btn btn-primary">
            </div>
        </div>
    </form>

    <?php if(isset($this->formRequerido)) echo $this->formRequerido;?>
</div>